basePath: /api/v1
definitions:
  ping.Response:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple API to learn Golang
  title: Learning Golang API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - '"*/*"'
      description: ping the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.Response'
      summary: ping the server
      tags:
      - healthcheck
swagger: "2.0"
