basePath: /api/v1
definitions:
  ping.Response:
    properties:
      message:
        type: string
    type: object
  programming.Response:
    properties:
      uuid:
        type: string
    type: object
info:
  contact: {}
  description: This is a simple API to learn Golang
  title: Learning Golang API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - '"*/*"'
      description: ping the server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.Response'
      summary: ping the server
      tags:
      - healthcheck
  /programming/uuid:
    post:
      consumes:
      - '"*/*"'
      description: create a new UUID
      parameters:
      - description: whether to exclude hyphens in the UUID
        in: query
        name: no-hyphens
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/programming.Response'
      summary: create a new UUID
      tags:
      - programming
swagger: "2.0"
